on: ["pull_request"]

name: Build and Test PR

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js ⚙️
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧
        run: |
          yarn install
          yarn run lint
          yarn run fixtures
          yarn run test:CI
